modLoader="javafml"
loaderVersion="[1,)"
license="GPL-3.0-only"

[[mods]]
modId="lunararc"
version="1.0.0"
displayName="LunarArc"
authors="Ampz Network"
description="LunarArc Hybrid Server Core"

[[mixins]]
config="lunararc.mixins.json"
